### PR TITLE
error message in gt_consolerunprocess.cpp

### PR DESCRIPTION
**Pull request by OliverKunc**
gave me a headache

### CODE REVIEW

**Comment by rainman110** [comment]
Good catch. Can you please change the PR to merge into branch 2.0.X? Then, this will be part of the next release instead of 2.1.

**Comment by rainman110** [comment]
@OliverKunc Could you please change the target branch of this Pull Request to be 2.0.X?

**Review by rainman110 — COMMENTED** [review]
Thanks for the contribution, welcome as a first gtlab contributor 😄 

If you like to integrate your changes into the 2.0 series, please make sure to change the target branch to 2.0.X. If we merge it into master, it will be included only in 2.1.

**Comment by OliverKunc** [comment]
done

**Comment by rainman110** [comment]
Oh no... I just wanted you to change the target branch, not to merge anything into your PR 😆 

Nevermind, let me fix this

**Pull request merged**
