### PR TITLE
Activate warning for unknown classes only in dev mode

### PR DESCRIPTION
**Pull request by jensschmeink**
## Description
The widget entries for unknown classes is only shown in dev mode

## Checklist:

- [ ] A test for the new functionality was added (if applicable).
- [ ] All tests run without failure.
- [ ] The changelog has been extended, if this MR contains important changes from the users's point of view.
- [ ] The new code complies with the GTlab's style guide.
- [ ] New interface methods / functions are exported via `EXPORT`. Non-interface functions are NOT exported.
- [ ] The number of code quality warnings is not increasing.

### CODE REVIEW

**Comment by jensschmeink** [comment]
Could be reviewed. Is a simple change to start show the dialog for unknown classes only in dev mode

**Comment by rainman110** [comment]
@jensschmeink How can I even show the unkown classes dialog (before this change). I tried to open a project using predesign and removed  the predesign module first. Then I don't get this dialog but only the "unknown module" dialog.

**Comment by jensschmeink** [comment]
> @jensschmeink How can I even show the unkown classes dialog (before this change)? I tried to open a project using predesign and removed the predesign module first. Then I don't get this dialog but only the "unknown module" dialog.

It is the same dialog but another page

**Comment by rainman110** [comment]
> > @jensschmeink How can I even show the unkown classes dialog (before this change)? I tried to open a project using predesign and removed the predesign module first. Then I don't get this dialog but only the "unknown module" dialog.
> 
> It is the same dialog but another page

I just have the page unknown modules:
image

**Comment by jensschmeink** [comment]
> > > @jensschmeink How can I even show the unkown classes dialog (before this change)? I tried to open a project using predesign and removed the predesign module first. Then I don't get this dialog but only the "unknown module" dialog.
> > 
> > 
> > It is the same dialog but another page
> 
> I just have the page unknown modules: image

I think a module package is not shown if it is unknown and so non of your predesign objects are tried to be constructed. To reproduce add a predesign calculator to one process.

**Comment by rainman110** [comment]
Okay, I could reproduce it.

**Review by rainman110 — CHANGES_REQUESTED** [review]
Please add to changelog

**Comment by rainman110** [comment]
@jensschmeink With your code changes, I still get the error dialog ?! I am not in dev mode.

image

**Comment by jensschmeink** [comment]
> @jensschmeink With your code changes, I still get the error dialog ?! I am not in dev mode.
> 
> image

Yes, you get it as long there is also found an unknown module. If the unknown classes would be the only reason to show the warning it is not shown anymore

**Comment by rainman110** [comment]
I think the problem is, that the popup opens up, because it also has unknown modules. What are the cases, when you have all modules but still unknwn classes?

**Comment by jensschmeink** [comment]
> I think the problem is, that the popup opens up, because it also has unknown modules. What are the cases, when you have all modules but still unknwn classes?

If you have unkown modules but you save your project. Then the usage of the module is no longer registered in the project and there is no comparison of the footprints failing. But the classes use din the project are till unknown

**Comment by rainman110** [comment]
> If you have unkown modules but you save your project.

**Review by rainman110 — APPROVED** [review]

**Comment by jensschmeink** [comment]
> > If you have unkown modules but you save your project.
> 
> Okay, this sounds dangerous to me. Just by saving, I loose the connection to the module? Should we fix this (in a separate issue)? Or is this intentional?

I'm not completely sure about that behaviour, so we should check it, discuss it and repair it in another issue

**Pull request merged**
